name: Documentation Request
description: Request new or improved documentation
title: "[DOCS]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template to request documentation improvements or new documentation.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation is this about?
      options:
        - API Reference
        - Tutorial
        - How-to Guide
        - Conceptual Explanation
        - FAQ
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe what documentation is needed or what should be improved.
      placeholder: Explain the documentation need...
    validations:
      required: true

  - type: textarea
    id: current-state
    attributes:
      label: Current State
      description: If applicable, describe the current state of the documentation.
      placeholder: Current documentation status...
    validations:
      required: false

  - type: textarea
    id: suggested-content
    attributes:
      label: Suggested Content
      description: If you have suggestions for the content, describe them here.
      placeholder: Suggested content or structure...
    validations:
      required: false
